# TokyoNight Alacritty Colors
[colors]

  # Default colors
  [colors.primary]
  background = '0x1a1b26'
  foreground = '0xc0caf5'

  # Normal colors
  [colors.normal]
  black = '0x15161e'
  red = '0xf7768e'
  green = '0x9ece6a'
  yellow = '0xe0af68'
  blue = '0x7aa2f7'
  magenta = '0xbb9af7'
  cyan = '0x7dcfff'
  white = '0xa9b1d6'

  # Bright colors
  [colors.bright]
  black = '0x414868'
  red = '0xf7768e'
  green = '0x9ece6a'
  yellow = '0xe0af68'
  blue = '0x7aa2f7'
  magenta = '0xbb9af7'
  cyan = '0x7dcfff'
  white = '0xc0caf5'


[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[cursor]
blink_interval = 750
vi_mode_style = "Underline"

[cursor.style]
blinking = "On"
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 22.0

[font.normal]
family = "Fira Code"
style = "Regular"

[font.bold]
family = "Fira Code"
style = "Bold"

[font.italic]
family = "Fira Code"
style = "Italic"

[window]
opacity = 0.5
title = "Ares Control Center"

